version: "3.9"

services:
  backend:
    build:
      context: ./submodules/backend
      dockerfile: Dockerfile
    env_file:
      - ./submodules/backend/.env
    environment:
      - HTTPS_PROXY=http://cache.univ-nantes.fr:3128/
      - HTTP_PROXY=http://cache.univ-nantes.fr:3128/
      - NO_PROXY=127.0.0.1,localhost
      - USERS_FILE_PATH=/app/dashboard-data-admin/users.json
    volumes:
      - ./submodules/backend/data:/app/data
      - ../dashboard-data-admin:/app/dashboard-data-admin
    ports:
      - "8091:8091"
    restart: unless-stopped

  leafwriter:
    build:
      context: ./leafwriter
      dockerfile: Dockerfile
      args:
        - ROUTER_BASE=/tei
    environment:
      - AUTH_API_URL=${BACKEND_PUBLIC_URL:-http://localhost:8091}
      - KEYCLOAK_URL=
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    depends_on:
      - backend
      - leafwriter
    restart: unless-stopped
