version: "3.9"

services:
  backend:
    build:
      context: ./submodules/backend
      dockerfile: Dockerfile
    env_file:
      - ./submodules/backend/.env
    ports:
      - "8091:8091"
    restart: unless-stopped

  leafwriter:
    build:
      context: ./leafwriter
      dockerfile: Dockerfile
    environment:
      - AUTH_API_URL=http://localhost:8091
      - KEYCLOAK_URL=
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    depends_on:
      - backend
      - leafwriter
    restart: unless-stopped
